const upcomingEvents = [
  {
    id: 1,
    title: 'Event One',
    month: 'January',
    date: '1',
    time: '18:00',
    venue: 'Venue One UON Hall 5',
    note: 'This is the first upcoming event.',
  },
  {
    id: 2,
    title: 'Event Two',
    month: 'September',
    date: '2',
    time: '20:00',
    venue: 'Venue Two',
    note: 'This is the second upcoming event.',
  },
  {
    id: 3,
    title: 'Event Three',
    month: 'August',
    date: '3',
    time: '17:00',
    venue: 'Venue Three',
    note: 'This is the third upcoming event.',
  },
  {
    id: 4,
    title: 'Event Four',
    month: 'February',
    date: '4',
    time: '19:00',
    venue: 'Venue Four',
    note: 'This is the fourth upcoming event.',
  },
  {
    id: 5,
    title: 'Event Five',
    month: 'June',
    date: '11',
    time: '16:00',
    venue: 'Venue Five',
    note: 'This is the fifth upcoming event.',
  },
  {
    id: 6,
    title: 'Event Six',
    month: 'September',
    date: '4',
    time: '21:00',
    venue: 'Venue Six',
    note: 'This is the sixth upcoming event.',
  },
  {
    id: 7,
    title: 'Event Seven',
    month: 'April',
    date: '8',
    time: '18:30',
    venue: 'Venue Seven',
    note: 'This is the seventh upcoming event.',
  },
  {
    id: 8,
    title: 'Event Eight',
    month: 'December',
    date: '9',
    time: '20:30',
    venue: 'Venue Eight',
    note: 'This is the eighth upcoming event.',
  },
];

// Command prompt: 'Add data called upcoming evnts with time, id, venue, date, title and note, make 8 such '
